# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Rainy Shiny Cloudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rainy Shiny Cloudy
  pod 'Alamofire', '~> 4.0'
end
